version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR started on `date`
      - aws --version
      - echo Logging into Amazon ECR....
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 320103368347.dkr.ecr.us-east-1.amazonaws.com
      - echo setting repository URI....
      - REPOSITORY_URI=320103368347.dkr.ecr.us-east-1.amazonaws.com/ecomvision_cdcipipepline
      - echo setting image tag....
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo building and tagging started image on `date`
      - echo running mvn clean install...
      - mvn clean install
      - echo building the Docker image...
      - docker build -t 320103368347.dkr.ecr.us-east-1.amazonaws.com/ecomvision_cdcipipepline:latest .
      - echo Tagging the Docker image...
      - docker tag 320103368347.dkr.ecr.us-east-1.amazonaws.com/ecomvision_cdcipipepline:latest 320103368347.dkr.ecr.us-east-1.amazonaws.com/ecomvision_cdcipipepline:build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  post_build:
    commands:
      - echo pushing Docker image to Amazon ECR started on `date`
      - echo pushing to repository...
      - docker push 320103368347.dkr.ecr.us-east-1.amazonaws.com/ecomvision_cdcipipepline:latest
      - docker push 320103368347.dkr.ecr.us-east-1.amazonaws.com/ecomvision_cdcipipepline:build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo setting container name...
      - DOCKER_CONTAINER_NAME=cicdcontainer
      - echo writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo printing imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json

