

MONGODB_PASSWORD: helloworld
DATABASE_NAME: Admin-Dashboard-react-spring


#Server config
CONTAINER_PORT: 8000
ACTIVE_PROFILE: dev

#Email config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: marckenlygbeau@gmail.com
EMAIL_PASSWORD: cxmjrheikeieobqv
VERIFY_EMAIL_HOST: http://localhost:3000

JWT_EXPIRATION: 432_000_000
JWT_SECRET: A39F4B58F8AC74938857618EDB02019AE4919A1A7635A3F756F6C7833C34675B66DF1CEF019EA1371ECC26EEE1FA75160D00B56BC57550708D9C1A308A3D8103